title: Synergistic Finance Official Docs
description: The official docs for Synergistic Finance 
theme: just-the-docs

url: https://CWolffSYNE.github.io/Synergistic-Finance

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
